### ISSUE TITLE
Facebook dead link

### ISSUE THREAD

**Issue by ZachAndrews98** [burrowss/burrowss.github.io#1]
If a user clicks on the Facebook icon at the bottom of the screen it leads to a 404 page. So you should either fix the link that it goes to or remove the link altogether.
![404](https://cloud.githubusercontent.com/assets/15204124/22665742/ddcda59c-ec83-11e6-84b5-3488ca4f5e9c.png)

**Comment by burrowss** [comment]
Fixed it. Thank you!
