### ISSUE TITLE
Keyboard article 

### ISSUE THREAD

**Issue by vanslykej** [burrowss/burrowss.github.io#2]
In the commit, cffb102ca871912e501081edf260d7ebd16429ed, there are a few issues:
* first paragraph, change then to than
* just a suggestion but maybe change the semicolon in the first paragraph to a colon
* in the second paragraph about seven lines down I would probably remove the comma after switches
* spelled references wrong at the end
* at the end it is good how you explain how the internet has helped, however I would maybe add a little more of that spread throughout the article

**Comment by burrowss** [comment]
Thanks for the feedback. I'll definitely take your last point into account while editing.

**Comment by burrowss** [comment]
I have fixed the grammar mistakes you have pointed out. Please let me know if you find anything else

**Comment by vanslykej** [comment]
I think everything looks good and the changes you made have made your writing very compelling. Great job!
