### ISSUE TITLE
Google and google accounts editing

### ISSUE THREAD

**Issue by cerdamejiaj** [burrowss/burrowss.github.io#3]
Paragraph two.

-  "passwords for other website" suggestion: "Another website"

- "consider what they want saved" suggestion: " want to be saved"

Paragraph three.
-  "Google but no where else." suggestion: "nowhere"

-put a comma after Instead,

-"cloud based" suggestion: "cloud-based"

Your article was greats, It had a few mistakes but overall good. I suggest reading it a  couple of times
got make sure that everything is good.

**Comment by burrowss** [comment]
Thank you for the suggestions. I have gone back and fixed these issues as well as other grammar issues. If you have any other ideas of how to improve my article please let me know.
