### ISSUE TITLE
Internet piracy interview

### ISSUE THREAD

**Issue by vanslykej** [burrowss/burrowss.github.io#5]
In the commit, d0b24e18b337d4688fd7a12fa1298b3c996f5764, I would change a few things.
* I would try to wrap the entire work together a bit better. This is vague, so some suggestions would be to put the each answer right under the corresponding question so you don't have to scroll to see it.
* Some sort of concluding paragraph.
* Other than that I think it is pretty good. Make sure to address and give a review of what you thought of your colleague's answers in the conclusion.

**Comment by burrowss** [comment]
Thank you for the suggestions. I believe that I have improved the article to be better formatted and clearer. Please let me know if you have any other suggestions
