### ISSUE TITLE
Plagiarism Article

### ISSUE THREAD

**Issue by vanslykej** [burrowss/burrowss.github.io#6]
I really like the work that you've done. One thing I might suggest is maybe explaining how exactly teachers could become better trained to detect plagiarism as you suggest they should be. Also, although it is clear that your opinion is that the technological services like turnitin.com are handy however don't do enough to stop plagiarism, do you suggest that schools should use these services more often, or just keep it the same but also add other traditional methods? In essence are the services not doing enough because they don't work well enough, or is it because they aren't used enough in schools? Just some suggestions good work!

**Comment by burrowss** [comment]
Thank you for the feedback, I will try to clarify my stances. If there's any other improvements I can do, please let me know
